spring:
   application:
     name: eureka-service
server:
   port: 8302
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    server:
      waitTimeInMsWhenSyncEmpty: 0
zuul:
  prefix: /api
  routes:
    customer-service:
      path: /customer/**
      url: http://localhost:8300
    vehicle-service:
      path: /vehicle/**
      url: http://localhost:8301



